# Generated by Django 5.0.7 on 2024-11-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='derivedparameter',
            table='dvadmin_acmt_derived_parameter',
        ),
    ]
